/*
 * Decompiled with CFR 0.150.
 */
package loliland.launcher.client;

public enum ii1li00Land {
    I1O1I1LaNd,
    OOOIilanD,
    lI00OlAND,
    lli0OiIlAND,
    li0iOILAND,
    O1il1llOLANd,
    Oill1LAnD,
    lIOILand,
    lil0liLand,
    iilIi1laND,
    lli011lLANd,
    l0illAND,
    IO11O0LANd,
    l11lLANd,
    lO110l1LANd,
    l0iIlIO1laNd,
    iOIl0LAnD,
    iIiO00OLaNd,
    ii1li00Land,
    IOI1LaNd,
    lI00ilAND,
    l0l00lAND,
    iOl10IlLAnd,
    lIiIii1LAnD,
    II1Iland,
    l0IO0LAnd,
    liOIOOLANd,
    II1i1l0laND,
    OOOliOOllANd,
    IiiilAnD,
    ll1ILAnd,
    l1i00lLAnD,
    lili0l0laNd,
    liIIllIland,
    l0Oil0IILAnd,
    l00OlIlAnd,
    liO1Oli1lanD,
    OI1II1OIlanD,
    lliliilanD,
    OO1Oi0LAnD,
    l01l0OilANd,
    Iil0IOlAND,
    lOOllANd,
    iOIOOilanD,
    illiLanD,
    OO10lO1LANd,
    II1II0laND,
    i0IIlOLANd,
    li0ii01laND,
    l0lllAND,
    l0lOiOlAnd,
    i100laND;

}

